imports:
    - { resource: 'parameters.yml'}
    - { resource: 'security.yml'}

twig:
    globals:
        techpromux_configurator: '@techpromux_configuration.manager.configurator'


sonata_media:
    contexts:
        techpromux_configuration_media_image:
            providers:
                - sonata.media.provider.image

            formats:
                admin:    { width: 75, quality: 75}
                abstract: { width: 100, quality: 100}
                small:    { width: 300, quality: 100}
                large:    { width: 750, quality: 100}
                wide:     { width: 820, quality: 100}   

sonata_admin:
    dashboard:
        blocks:
            - { position: right, type: sonata.admin.block.admin_list, settings: { groups: [techpromux_configurations_admin] } }

        groups:
            techpromux_configurations_admin:
                label: System Configurations
                label_catalogue: TechPromuxDynamicConfigurationBundle
                icon: '<i class="glyphicon glyphicon-cog"></i>'
                items:
                    - techpromux_configuration.admin.custom_configuration
                    - techpromux_configuration.admin.owner_configuration

