security:
    role_hierarchy:
        
        # sonata roles
        
        #ROLE_TECHPROMMUX_CONFIGURATION__CUSTOM_CONFIGURATION_ADMIN:

        #    - ROLE_DASHBOARD_USER
        #    - ROLE_TECHPROMUX_CONFIGURATION_ADMIN_CUSTOM_CONFIGURATION_LIST
        #    #- ROLE_TECH_PROMUX_CONFIGURATION_ADMIN_CUSTOM_CONFIGURATION_VIEW
        #    - ROLE_TECHPROMUX_CONFIGURATION_ADMIN_CUSTOM_CONFIGURATION_CREATE
        #    - ROLE_TECHPROMUX_CONFIGURATION_ADMIN_CUSTOM_CONFIGURATION_EDIT
        #    - ROLE_TECHPROMUX_CONFIGURATION_ADMIN_CUSTOM_CONFIGURATION_DELETE
            #- ROLE_TECH_PROMUX_CONFIGURATION_ADMIN_CUSTOM_CONFIGURATION_EXPORT
        
        #ROLE_TECHPROMUX_CONFIGURATION__OWNER_CONFIGURATION_ADMIN:

        #    - ROLE_DASHBOARD_USER
        #    - ROLE_TECHPROMUX_CONFIGURATION_ADMIN_OWNER_CONFIGURATION_LIST
            #- ROLE_TECH_PROMUX_CONFIGURATION_ADMIN_OWNER_CONFIGURATION_VIEW
            #- ROLE_TECH_PROMUX_CONFIGURATION_ADMIN_OWNER_CONFIGURATION_CREATE
        #    - ROLE_TECHPROMUX_CONFIGURATION_ADMIN_OWNER_CONFIGURATION_EDIT
            #- ROLE_TECH_PROMUX_CONFIGURATION_ADMIN_OWNER_CONFIGURATION_DELETE
            #- ROLE_TECH_PROMUX_CONFIGURATION_ADMIN_OWNER_CONFIGURATION_EXPORT

        
