services:
   # Manager Services

    techpromux_dynamic_configuration.manager.dynamic_variable:
        class:  TechPromux\DynamicConfigurationBundle\Manager\DynamicVariableManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setUtilDynamicConfigurationManager, ['@techpromux_dynamic_configuration.manager.util_dynamic_configuration']]

    techpromux_dynamic_configuration.manager.default_resource_owner:
        alias: techpromux.manager.default_resource_owner

    techpromux_dynamic_configuration.manager.owner_variable:
        class:  TechPromux\DynamicConfigurationBundle\Manager\OwnerVariableManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setResourceOwnerManager,['@techpromux_dynamic_configuration.manager.default_resource_owner']]
            - [ setDynamicVariableManager,['@techpromux_dynamic_configuration.manager.dynamic_variable']]
            - [ setUtilDynamicConfigurationManager, ['@techpromux_dynamic_configuration.manager.util_dynamic_configuration']]

    techpromux_dynamic_configuration.manager.util_dynamic_configuration:
        class:  TechPromux\DynamicConfigurationBundle\Manager\UtilDynamicConfigurationManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setDynamicVariableManager,['@techpromux_dynamic_configuration.manager.dynamic_variable']]
            - [ setOwnerVariableManager,['@techpromux_dynamic_configuration.manager.owner_variable']]
