services:
#    tech_promux_configuration.example:
#        class: TechPromux\Bundle\ConfigurationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    # Types Services

    techpromux_configuration.type.text:
        class: TechPromux\Bundle\ConfigurationBundle\Type\TextConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.textarea:
        class: TechPromux\Bundle\ConfigurationBundle\Type\TextareaConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.textarea-html:
        class: TechPromux\Bundle\ConfigurationBundle\Type\TextareaHtmlConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.email:
        class: TechPromux\Bundle\ConfigurationBundle\Type\EmailConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.integer:
        class: TechPromux\Bundle\ConfigurationBundle\Type\IntegerConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.number:
        class: TechPromux\Bundle\ConfigurationBundle\Type\NumberConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.boolean:
        class: TechPromux\Bundle\ConfigurationBundle\Type\BooleanConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.url:
        class: TechPromux\Bundle\ConfigurationBundle\Type\UrlConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.color_rgb:
        class: TechPromux\Bundle\ConfigurationBundle\Type\ColorRGBConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.color_rgba:
        class: TechPromux\Bundle\ConfigurationBundle\Type\ColorRGBAConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.date:
        class: TechPromux\Bundle\ConfigurationBundle\Type\DateConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.time:
        class: TechPromux\Bundle\ConfigurationBundle\Type\TimeConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.datetime:
        class: TechPromux\Bundle\ConfigurationBundle\Type\DatetimeConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.country:
        class: TechPromux\Bundle\ConfigurationBundle\Type\CountryConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.language:
        class: TechPromux\Bundle\ConfigurationBundle\Type\LanguageConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.locale:
        class: TechPromux\Bundle\ConfigurationBundle\Type\LocaleConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.timezone:
        class: TechPromux\Bundle\ConfigurationBundle\Type\TimezoneConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.image:
        class: TechPromux\Bundle\ConfigurationBundle\Type\ImageConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}
        calls:
            - [ setServiceContainer,['@service_container']]

    techpromux_configuration.type.choice_select_same_key_value:
        class: TechPromux\Bundle\ConfigurationBundle\Type\ChoiceSelectSameKeyValueConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.choice_select_different_key_value:
        class: TechPromux\Bundle\ConfigurationBundle\Type\ChoiceSelectDifferentKeyValueConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.choice_radio_same_key_value:
        class: TechPromux\Bundle\ConfigurationBundle\Type\ChoiceRadioSameKeyValueConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.choice_radio_different_key_value:
        class: TechPromux\Bundle\ConfigurationBundle\Type\ChoiceRadioDifferentKeyValueConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.choice_checkbox_same_key_value:
        class: TechPromux\Bundle\ConfigurationBundle\Type\ChoiceCheckboxSameKeyValueConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.choice_checkbox_different_key_value:
        class: TechPromux\Bundle\ConfigurationBundle\Type\ChoiceCheckboxDifferentKeyValueConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_text:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleTextConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_textarea:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleTextareaConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_textarea_html:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleTextareaHtmlConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple-email:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleEmailConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_integer:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleIntegerConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_number:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleNumberConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_boolean:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleBooleanConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_url:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleUrlConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_color_rgb:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleColorRGBConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_color_rgba:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleColorRGBAConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_date:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleDateConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_time:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleTimeConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple_datetime:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleDatetimeConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple-country:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleCountryConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple-language:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleLanguageConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple-locale:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleLocaleConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple-timezone:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleTimezoneConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}

    techpromux_configuration.type.multiple-key-value:
        class: TechPromux\Bundle\ConfigurationBundle\Type\MultipleKeyValueConfigurationType
        tags:
            - { name: techpromux_configuration.type.configuration}




