services:
#    tech_promux_variable.example:
#        class:  TechPromux\DynamicDynamicConfigurationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    # Admin Services

    techpromux_dynamic_configuration.admin.dynamic_variable:
        class:  TechPromux\DynamicConfigurationBundle\Admin\DynamicVariableAdmin
        arguments: [~,  TechPromux\DynamicConfigurationBundle\Entity\DynamicVariable, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_configuration_admin, label: 'System Variables'}
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicConfigurationBundle']]
            - [ setResourceManager,['@techpromux_dynamic_configuration.manager.dynamic_variable']]
