services:
#    tech_promux_variable.example:
#        class:  TechPromux\DynamicDynamicConfigurationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    # Types Services

    techpromux_dynamic_configuration.type.text:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\TextVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.textarea:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\TextareaVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.textarea-html:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\TextareaHtmlVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.email:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\EmailVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.integer:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\IntegerVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.number:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\NumberVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.boolean:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\BooleanVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.url:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\UrlVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.color_rgb:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\ColorRGBVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.color_rgba:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\ColorRGBAVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.date:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\DateVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.time:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\TimeVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.datetime:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\DatetimeVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.country:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\CountryVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.language:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\LanguageVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.locale:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\LocaleVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.timezone:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\TimezoneVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.image:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\ImageVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}
        calls:
            - [ setServiceContainer,['@service_container']]
            - [ setEntityManager,['@doctrine.orm.default_entity_manager']]


    techpromux_dynamic_configuration.type.choice_select_same_key_value:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\ChoiceSelectSameKeyValueVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.choice_select_different_key_value:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\ChoiceSelectDifferentKeyValueVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.choice_radio_same_key_value:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\ChoiceRadioSameKeyValueVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.choice_radio_different_key_value:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\ChoiceRadioDifferentKeyValueVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.choice_checkbox_same_key_value:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\ChoiceCheckboxSameKeyValueVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.choice_checkbox_different_key_value:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\ChoiceCheckboxDifferentKeyValueVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_text:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleTextVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_textarea:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleTextareaVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_textarea_html:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleTextareaHtmlVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple-email:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleEmailVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_integer:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleIntegerVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_number:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleNumberVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_boolean:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleBooleanVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_url:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleUrlVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_color_rgb:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleColorRGBVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_color_rgba:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleColorRGBAVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_date:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleDateVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_time:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleTimeVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple_datetime:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleDatetimeVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple-country:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleCountryVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple-language:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleLanguageVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple-locale:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleLocaleVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple-timezone:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleTimezoneVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}

    techpromux_dynamic_configuration.type.multiple-key-value:
        class:  TechPromux\DynamicConfigurationBundle\Type\Variable\MultipleKeyValueVariableType
        tags:
            - { name: techpromux_dynamic_configuration.type.variable}




