services:
#    tech_promux_variable.example:
#        class:  TechPromux\DynamicDynamicConfigurationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    # Admin Services

    techpromux_dynamic_configuration.admin.dynamic_configuration:
        class:  TechPromux\DynamicConfigurationBundle\Admin\DynamicVariableAdmin
        arguments: [~,  TechPromux\DynamicConfigurationBundle\Entity\DynamicVariable, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_configuration_admin, label: 'General Variables'}
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicConfigurationBundle']]
            - [ setResourceManager,['@techpromux_dynamic_configuration.manager.dynamic_variable']]

    techpromux_dynamic_configuration.admin.owner_variable:
        class:  TechPromux\DynamicConfigurationBundle\Admin\OwnerVariableAdmin
        arguments: [~,  TechPromux\DynamicConfigurationBundle\Entity\OwnerVariable, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_dynamic_configuration_admin, label: 'Owner Variables', show_in_dashboard: true}
        calls:
            - [ setTranslationDomain,['TechPromuxDynamicConfigurationBundle']]
            - [ setResourceManager,['@techpromux_dynamic_configuration.manager.owner_variable']]
