services:
#    tech_promux_configuration.example:
#        class: TechPromux\Bundle\DynamicDynamicConfigurationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    # Types Services

    techpromux_dynamic_configuration.type.text:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\TextConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.textarea:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\TextareaConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.textarea-html:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\TextareaHtmlConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.email:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\EmailConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.integer:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\IntegerConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.number:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\NumberConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.boolean:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\BooleanConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.url:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\UrlConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.color_rgb:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\ColorRGBConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.color_rgba:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\ColorRGBAConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.date:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\DateConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.time:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\TimeConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.datetime:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\DatetimeConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.country:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\CountryConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.language:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\LanguageConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.locale:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\LocaleConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.timezone:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\TimezoneConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.image:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\ImageConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}
        calls:
            - [ setServiceContainer,['@service_container']]

    techpromux_dynamic_configuration.type.choice_select_same_key_value:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\ChoiceSelectSameKeyValueConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.choice_select_different_key_value:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\ChoiceSelectDifferentKeyValueConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.choice_radio_same_key_value:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\ChoiceRadioSameKeyValueConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.choice_radio_different_key_value:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\ChoiceRadioDifferentKeyValueConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.choice_checkbox_same_key_value:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\ChoiceCheckboxSameKeyValueConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.choice_checkbox_different_key_value:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\ChoiceCheckboxDifferentKeyValueConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_text:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleTextConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_textarea:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleTextareaConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_textarea_html:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleTextareaHtmlConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple-email:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleEmailConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_integer:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleIntegerConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_number:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleNumberConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_boolean:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleBooleanConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_url:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleUrlConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_color_rgb:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleColorRGBConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_color_rgba:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleColorRGBAConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_date:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleDateConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_time:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleTimeConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple_datetime:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleDatetimeConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple-country:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleCountryConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple-language:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleLanguageConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple-locale:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleLocaleConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple-timezone:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleTimezoneConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}

    techpromux_dynamic_configuration.type.multiple-key-value:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Type\Configuration\MultipleKeyValueConfigurationType
        tags:
            - { name: techpromux_dynamic_configuration.type.configuration}




