imports:
    - { resource: 'services_types_variables.yml'}
    - { resource: 'services_managers.yml'}
    - { resource: 'services_admins.yml'}

services:

#    tech_promux_variable.example:
#        class:  TechPromux\DynamicDynamicConfigurationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
