services:
   # Manager Services

    techpromux_dynamic_configuration.manager.dynamic_variable:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Manager\DynamicVariableManager
        arguments: [~]
        tags:
            - { name: techpromux.entity_manager}
        calls:
            - [ setServiceContainer,['@service_container']]
            - [ setUtilDynamicConfigurationManager, ['@techpromux_dynamic_configuration.manager.util_dynamic_configuration']]

    techpromux_dynamic_configuration.manager.owner_variable:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Manager\OwnerVariableManager
        arguments: [~]
        tags:
            - { name: techpromux.entity_manager}
        calls:
            - [ setServiceContainer,['@service_container']]
            - [ setDynamicVariableManager,['@techpromux_dynamic_configuration.manager.dynamic_variable']]
            - [ setUtilDynamicConfigurationManager, ['@techpromux_dynamic_configuration.manager.util_dynamic_configuration']]

    techpromux_dynamic_configuration.manager.util_dynamic_configuration:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Manager\UtilDynamicConfigurationManager
        arguments: [~]
        calls:
            - [ setServiceContainer,['@service_container']]
            - [ setDynamicVariableManager,['@techpromux_dynamic_configuration.manager.dynamic_variable']]
            - [ setOwnerVariableManager,['@techpromux_dynamic_configuration.manager.owner_variable']]
