imports:
    - { resource: 'services_types_configuration.yml'}
    - { resource: 'services_managers.yml'}
    - { resource: 'services_admins.yml'}

services:

#    tech_promux_configuration.example:
#        class: TechPromux\Bundle\DynamicDynamicConfigurationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
