services:
   # Manager Services

    techpromux_dynamic_configuration.manager.dynamic_variable:
        class:  TechPromux\DynamicConfigurationBundle\Manager\DynamicVariableManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
            - { name: techpromux.resource_manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setUtilDynamicConfigurationManager, ['@techpromux_dynamic_configuration.manager.util_dynamic_configuration']]

    techpromux_dynamic_configuration.manager.util_dynamic_configuration:
        class:  TechPromux\DynamicConfigurationBundle\Manager\UtilDynamicConfigurationManager
        arguments: [~]
        tags:
            - { name: techpromux.manager}
        calls:
            #- [ setServiceContainer,['@service_container']]
            - [ setDynamicVariableManager,['@techpromux_dynamic_configuration.manager.dynamic_variable']]
            #- [ setContextVariableManager,['@techpromux_dynamic_configuration.manager.context_variable']]
