services:
#    tech_promux_configuration.example:
#        class: TechPromux\Bundle\DynamicDynamicConfigurationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    # Admin Services

    techpromux_configuration.admin.custom_configuration:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Admin\CustomConfigurationAdmin
        arguments: [~, TechPromux\Bundle\DynamicConfigurationBundle\Entity\CustomConfiguration, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_configurations_admin, label: 'General Configurations'}

    techpromux_configuration.admin.owner_configuration:
        class: TechPromux\Bundle\DynamicConfigurationBundle\Admin\OwnerConfigurationAdmin
        arguments: [~, TechPromux\Bundle\DynamicConfigurationBundle\Entity\OwnerConfiguration, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: techpromux_configurations_admin, label: 'Owner Configurations', show_in_dashboard: true}
